### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by Magic-Dust** [usa-local-epg/usa-locals#1]
EPG is brilliant, thanks for the effort.   Any chance of leaving an unzipped, gzip or .xz copy for use with IPT merge?

**Comment by usa-local-epg** [comment]
Thanks! Yeah, I can look into gzip or xz. I'd really like to upload it uncompressed, but github's file size limit of 25 MB is a bit of a hurdle.

**Comment by usa-local-epg** [comment]
gzip and xz versions added. I'll work on automating them, but in the meantime, doing it manually takes me like 45 seconds.

If you have any other issues or I can help otherwise, please let me know.

**Comment by Magic-Dust** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Thanks a million!                                                                                                                                             Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                           From: ***@***.***Sent: April 7, 2021 3:31 PMTo: ***@***.***Reply-to: ***@***.***Cc: ***@***.***; ***@***.***Subject: Re: [usa-local-epg/usa-locals] Compression (#1)  
gzip and xz versions added. I'll work on automating them, but in the meantime, doing it manually takes me like 45 seconds.
If you have any other issues or I can help otherwise, please let me know.
